/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include "uart.h"
#include "dht11.h"
#include "display.h"

int main(void)
{
     *pAHB1ENR |= (1<<0);

 TIM2_Init();

 UART2_Init(115200);
 DHT11_Data sensor;
 DHT11_Status status;

 while(1)
 {
     status = DHT11_ReadData(&sensor);

     switch(status)
     {
         case DHT11_OK:
             DisplaySensorData(&sensor);
             break;

         case DHT11_ERROR_NO_RESPONSE:
             UART2_SendString("Error: No Response\r\n");
             break;

         case DHT11_ERROR_CHECKSUM:
             UART2_SendString("Error: Checksum Failed\r\n");
             break;

         default:
             UART2_SendString("Unknown Error\r\n");
             break;
     }

     delay_ms(1000);
 }


}













