/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include <stdint.h>
#include "uart.h"
#include "dht11.h"

int main(void)
{
     *pAHB1ENR |= (1<<0);

 TIM2_Init();

 UART2_Init(115200);

 DHT11_Data sensor;

    while(1)
    {
    	if(DHT11_ReadData(&sensor))
    	{
    	    UART2_SendString("Temperature : ");

    	    UART2_SendNumber(sensor.temperature);

    	    UART2_SendString(" C\r\n");

    	    UART2_SendString("Humidity : ");

    	    UART2_SendNumber(sensor.humidity);

    	    UART2_SendString(" %\r\n\r\n");

    	    delay_ms(1000);
    	}


    }

}













